# Generated by Django 4.1.4 on 2022-12-30 10:37

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_image', models.ImageField(upload_to='assets/img/doctors/')),
                ('doctor_title', models.CharField(max_length=40)),
                ('doctor_description', models.TextField()),
                ('doctor_twitter', models.URLField(blank=True, null=True)),
                ('doctor_facebook', models.URLField(blank=True, null=True)),
                ('doctor_instagram', models.URLField(blank=True, null=True)),
                ('doctor_youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=14)),
                ('department', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='mainApp.doctor')),
            ],
        ),
    ]
